kind: pipeline
type: docker
name: Docker image build

trigger:
  branch:
    - test

environment:
  FRP_VERSION: 0.34.3

steps:
  - name: config
    image: alpine
    commands:
      - echo -n "$FRP_VERSION,latest" > .tags
      - sed -i -E "s/var_FRP_VERSION/$FRP_VERSION/" Dockerfile
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quackerd/private_test
