kind: pipeline
type: docker
name: default

trigger:
  branch:
    - test

environment:
  FRP_VERSION: 0.34.3

steps:
  - name: tag
    image: alpine
    commands:
      - echo -n "$FRP_VERSION,latest" > .tags

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quackerd/private_test
      build_args:
        - FRP_VERSION=$FRP_VERSION
