kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quackerd/frp
      tags: latest
